name: Linux Build

on:
  workflow_call:
    inputs:
      PUSH_IMAGE:
        type: boolean
        description: "Push image to registry"
        required: true
      GO_VERSION:
        type: string
        description: "Full Go version to use, e.g. 1.21.1"
        required: true
      NODE_VERSION:
        type: string
        description: "Node version to use, e.g. 18, 20 etc"
        required: true
      WAILS_VERSION:
        type: string
        description: "Wails version to use, e.g. v2.6.0"
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest

    timeout-minutes: 50

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate Docker Tag
        id: calculateDockerTag
        env:
          WAILS_VERSION: ${{ inputs.WAILS_VERSION }}
        run: |
          RELEASE_TAG="ghcr.io/abjrcode/cross-wails:$WAILS_VERSION" && echo $RELEASE_TAG && echo "releaseTag=$RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          push: ${{ inputs.PUSH_IMAGE }}
          tags: ${{ steps.calculateDockerTag.outputs.releaseTag }}
          load: false
          platforms: linux/amd64,linux/arm64
          cache-from: |
            type=registry,ref=ghcr.io/abjrcode/cross-wails/cache
          cache-to: type=registry,ref=ghcr.io/abjrcode/cross-wails/cache,mode=max
          build-args: |
            GO_VERSION=${{ inputs.GO_VERSION }}
            WAILS_VERSION=${{ inputs.WAILS_VERSION }}
            NODE_MAJOR_VERSION=${{ inputs.NODE_VERSION }}
