name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: cross-wails-pr-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  LinuxCI:
    if: ${{ !github.event.pull_request.draft }}

    uses: ./.github/workflows/build-linux.yaml

    permissions:
      contents: read
      packages: write

    with:
      PUSH_IMAGE: false
      GO_VERSION: "1.21.5"
      NODE_VERSION: "20"
      WAILS_VERSION: "v2.8.2"
